"""Generate Constat's standalone content pages into site/<name>/index.html.

Three pages, one shell, one stylesheet — the same brand tokens the landing page
uses, so a visitor never crosses a seam:

    /trust/          our own security answers, generated by our own engine
    /how-it-works/   the product flow, end to end
    /pricing/        what it costs, and what is not included

    .venv/bin/python scripts/build_pages.py

The trust page is genuinely generated: it runs the standard buyer question set
through the engine against our own corpus. The other two are written, and say so
by not claiming otherwise.
"""
from __future__ import annotations

import html
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from constat import brand, trustpage        # noqa: E402

SITE = ROOT / "site"
CONTACT = "dhruv.shahi07@gmail.com"

NAV = [("/", "Home"), ("/how-it-works/", "How it works"),
       ("/pricing/", "Pricing"), ("/trust/", "Trust centre")]

CSS = """
.pg{max-width:1080px;margin:0 auto;padding:0 32px 96px}
.pg-top{display:flex;align-items:center;justify-content:space-between;gap:24px;flex-wrap:wrap;
padding:22px 0;border-bottom:1px solid var(--line-hair)}
.pg-top nav{display:flex;gap:22px;flex-wrap:wrap}
.pg-top a{color:var(--text-secondary);text-decoration:none;font:var(--type-mono-s);
letter-spacing:var(--tracking-caps);text-transform:uppercase}
.pg-top a:hover,.pg-top a.on{color:var(--signal)}
.pg-head{padding:72px 0 30px}
.pg-head h1{font-family:var(--font-display);font-size:clamp(34px,5vw,54px);line-height:1.05;
font-weight:400;letter-spacing:-0.02em;max-width:22ch}
.pg-head p{margin-top:20px;color:var(--text-secondary);font-size:17px;line-height:1.65;max-width:66ch}
h2.sec{font-family:var(--font-display);font-size:26px;font-weight:400;margin:52px 0 8px}
p.lede{color:var(--text-secondary);font-size:15.5px;line-height:1.75;max-width:70ch;margin-bottom:14px}
ul.pts{margin:12px 0 18px 20px} ul.pts li{color:var(--text-secondary);font-size:15px;line-height:1.75;margin-bottom:9px}
ul.pts b{color:var(--text-primary)}
.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:34px 0 8px}
.stat{background:var(--surface-card);border:1px solid var(--line-hair);padding:16px 18px}
.stat b{display:block;font-family:var(--font-display);font-size:30px;font-weight:400;line-height:1.1}
.stat span{display:block;margin-top:6px;font:var(--type-mono-s);letter-spacing:var(--tracking-caps);
text-transform:uppercase;color:var(--text-tertiary)}
.stat.on b{color:var(--signal)}
.note{border-left:2px solid var(--signal);background:var(--signal-wash);padding:16px 20px;
margin:26px 0;font-size:14.5px;line-height:1.7;color:var(--text-secondary)}
.note b{color:var(--text-primary)}
.steps{margin:26px 0;counter-reset:s}
.step{position:relative;padding:0 0 26px 54px;border-left:1px solid var(--line-hair);margin-left:16px}
.step:last-child{border-left-color:transparent;padding-bottom:0}
.step:before{counter-increment:s;content:counter(s);position:absolute;left:-16px;top:-3px;
width:32px;height:32px;border-radius:50%;background:var(--surface-raised);
border:1px solid var(--line-signal);color:var(--signal);
font:var(--type-mono-s);line-height:31px;text-align:center}
.step h3{font-size:16.5px;font-weight:600;margin-bottom:6px}
.step p{color:var(--text-secondary);font-size:15px;line-height:1.7;max-width:64ch}
.step .who{display:block;font:var(--type-mono-s);letter-spacing:var(--tracking-caps);
text-transform:uppercase;color:var(--signal-deep);margin-bottom:5px}
.tiers{display:grid;grid-template-columns:repeat(auto-fit,minmax(272px,1fr));gap:14px;margin:28px 0}
.tier{background:var(--surface-card);border:1px solid var(--line-hair);padding:24px}
.tier.on{border-color:var(--line-signal)}
.tier h3{font-size:17px;font-weight:600}
.tier .price{font-family:var(--font-display);font-size:30px;font-weight:400;margin:12px 0 2px}
.tier .unit{font:var(--type-mono-s);letter-spacing:var(--tracking-caps);text-transform:uppercase;
color:var(--text-tertiary)}
.tier ul{margin:16px 0 0 18px} .tier li{color:var(--text-secondary);font-size:14px;line-height:1.65;margin-bottom:7px}
.tier .who2{margin-top:16px;padding-top:14px;border-top:1px solid var(--line-hair);
color:var(--text-tertiary);font-size:13.5px;line-height:1.6}
.qa{background:var(--surface-card);border:1px solid var(--line-hair);border-left:2px solid var(--status-ok);
padding:18px 22px;margin-bottom:10px}
.qa.open{border-left-color:var(--bone-4);background:transparent}
.qa .q{font-weight:600;font-size:15px;margin-bottom:8px}
.qa .a{color:var(--text-secondary);font-size:14.5px;line-height:1.7}
.qa .prov{margin-top:12px;padding-top:10px;border-top:1px solid var(--line-hair);
font:var(--type-mono-s);color:var(--text-tertiary)}
.qa .req{font:var(--type-mono-s);color:var(--bone-3)}
.dom{margin:44px 0 12px;font:var(--type-mono-s);letter-spacing:var(--tracking-caps);
text-transform:uppercase;color:var(--text-tertiary)}
.pg-foot{margin-top:66px;padding-top:22px;border-top:1px solid var(--line-hair);
font:var(--type-mono-s);color:var(--text-tertiary);line-height:1.9}
.pg-foot a{color:var(--signal)}
"""


def esc(t) -> str:
    return html.escape(str(t), quote=False)


def shell(title: str, active: str, head: str, body: str, description: str) -> str:
    nav = "".join(f'<a href="{h}"{" class=\"on\"" if h == active else ""}>{esc(l)}</a>'
                  for h, l in NAV)
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{html.escape(description, quote=True)}">
<style>{brand.stylesheet(CSS)}</style></head><body>
<div class="pg">
<div class="pg-top"><nav>{nav}</nav>
<a href="mailto:{esc(CONTACT)}?subject=Constat">Get in touch</a></div>
{head}
{body}
<div class="pg-foot">
Constat &middot; page generated {date.today().isoformat()} &middot;
<a href="/">back to the product</a><br>
All customer data shown anywhere on this site is synthetic.
</div>
</div></body></html>"""


def head(h1: str, lede: str) -> str:
    return f'<div class="pg-head"><h1>{esc(h1)}</h1><p>{lede}</p></div>'


# --- /trust/ ------------------------------------------------------------------
def build_trust() -> tuple[str, dict]:
    r = trustpage.generate("constat", ROOT / "data" / "evidence",
                           display_name="Constat", today=date.today())
    by_domain: dict[str, list] = {}
    for a in r.answers:
        by_domain.setdefault(a.domain, []).append(a)

    blocks = []
    for domain, items in by_domain.items():
        blocks.append(f'<div class="dom">{esc(domain)}</div>')
        for a in items:
            if a.published:
                prov = "<br>".join(
                    f"{esc(c['source_id'])} &middot; v{esc(c['version'])} &middot; {esc(c['location'])}"
                    for c in a.citations)
                blocks.append(f'<div class="qa"><div class="q">{esc(a.question)}</div>'
                              f'<div class="a">{esc(a.answer)}</div>'
                              f'<div class="prov">{prov}</div></div>')
            else:
                blocks.append(f'<div class="qa open"><div class="q">{esc(a.question)}</div>'
                              f'<div class="req">Not published &mdash; our evidence does not '
                              f'support a self-serve answer. Ask us through security review.'
                              f'</div></div>')

    pct = round(r.deflection_rate * 100)
    body = f"""
<div class="stats">
<div class="stat on"><b>{pct}%</b><span>answered self-serve</span></div>
<div class="stat"><b>{len(r.shown)}</b><span>with citations</span></div>
<div class="stat"><b>{len(r.open_items)}</b><span>open &mdash; ask us</span></div>
<div class="stat"><b>{len(r.answers)}</b><span>standard questions</span></div>
</div>
<div class="note"><b>How to read this page.</b> An answer appears only when every claim in it is
supported by an approved, in-force document, and it names that document, its version and the
paragraph. We hold no certifications, so every certification question below is refused &mdash;
including ISO&nbsp;42001, where the only document on file is a roadmap, and a roadmap is not a
certificate.</div>
{''.join(blocks)}
"""
    page = shell("Trust centre — Constat", "/trust/",
                 head("Our own security answers, produced by our own engine.",
                      "Every answer below was generated by the system this page describes, from "
                      "our own evidence corpus, under the same gates that run for a customer. "
                      "Nothing here was written by hand. Questions our evidence cannot support "
                      "are listed as open rather than answered with something plausible &mdash; "
                      "which is the entire argument, applied to ourselves."),
                 body, "Constat's own security answers, generated by Constat.")
    return page, r.to_dict()


# --- /how-it-works/ -----------------------------------------------------------
def build_how() -> str:
    body = """
<h2 class="sec">The flow</h2>
<div class="steps">
  <div class="step"><span class="who">You &middot; a minute</span>
    <h3>Create a workspace</h3>
    <p>An email address and an organisation name. You get a workspace and a token, shown once.
    No credit card, no sales call, no demo request form.</p></div>

  <div class="step"><span class="who">You &middot; drag and drop</span>
    <h3>Upload your evidence, or seed the sample pack</h3>
    <p>Policies, standards, plans, attestations. PDF and Word, as they already exist. Each becomes
    a governed source with a type, a version, an owner and the dates it is in force between &mdash;
    because the gates reason about those, not about vibes. If you just want to see it work, seed
    the synthetic sample pack instead and skip straight to the run.</p></div>

  <div class="step"><span class="who">You &middot; paste or upload</span>
    <h3>Ask a question, or run the whole questionnaire</h3>
    <p>Ask a single buyer question and watch the gate path. Or upload the questionnaire the buyer
    actually sent and run all of it.</p></div>

  <div class="step"><span class="who">The engine &middot; minutes</span>
    <h3>Every answer is cited, or refused</h3>
    <p>Each answer names the document, version and paragraph it came from. Where the evidence is
    missing, expired, contradicted by another approved document, or the question is really a
    contractual commitment, the engine declines and names the gap and its owner. It does not
    produce a plausible sentence to fill the cell.</p></div>

  <div class="step"><span class="who">You &middot; the part only you can do</span>
    <h3>A named person signs it off</h3>
    <p>These are material security representations, so a person takes responsibility for them.
    Approve what the evidence supports. Where you want to answer something the evidence does not
    support, you write it, and it is recorded as authored by you &mdash; visibly not
    evidence-backed. Every decision joins a hash-chained log.</p></div>

  <div class="step"><span class="who">You &middot; same session</span>
    <h3>Export and send</h3>
    <p>The buyer's own workbook, answered, with structure intact and every answer carrying its
    provenance. Plus the working paper showing how each answer was reached.</p></div>
</div>

<h2 class="sec">What we never do</h2>
<ul class="pts">
  <li><b>Never train on your content.</b> There is no training pipeline, and no model is adapted
      on your evidence, your questionnaires or your answers.</li>
  <li><b>Never send a whole document.</b> One question and at most four excerpts cross to the
      model. The documents stay in your workspace and are hard deleted after fourteen days.</li>
  <li><b>Never mix workspaces.</b> Each is a separate evidence store; there is no code path that
      loads two together, and that is asserted by test on every change.</li>
  <li><b>Never publish an answer nobody signed.</b></li>
</ul>

<div class="note"><b>Which key drafts your answers is your choice, and it matters.</b> On the free
demo key, provider terms permit them to use submitted content to improve their services &mdash;
fine for a published SOC&nbsp;2 report, wrong for a confidential runbook, which is why the demo
accepts public evidence only. Bring your own key and your own contract terms apply. Take a managed
workspace and a no-training commitment becomes a contract term rather than a marketing line.
<a href="/pricing/">See the three modes &rarr;</a></div>
"""
    return shell("How it works — Constat", "/how-it-works/",
                 head("Upload your evidence. Send the questionnaire back today.",
                      "No deployment, no integration project, no six-week onboarding. A workspace, "
                      "your documents, and answers that either cite an approved source or refuse "
                      "and tell you what is missing."),
                 body, "How a Constat engagement runs, end to end.")


# --- /pricing/ ----------------------------------------------------------------
def build_pricing() -> str:
    body = """
<div class="tiers">
  <div class="tier">
    <h3>Demo</h3><div class="price">Free</div><div class="unit">our key</div>
    <ul>
      <li>A workspace and the synthetic sample pack</li>
      <li>Ask questions, run a full questionnaire, export the workbook</li>
      <li>Every gate live &mdash; refusals, contradictions, staleness</li>
      <li><b>Public evidence only</b></li>
    </ul>
    <div class="who2">Free-tier provider terms permit them to use submitted content to improve
    their services. A published SOC&nbsp;2 report loses nothing by that. Your confidential
    runbooks would, so the demo does not accept them.</div>
  </div>

  <div class="tier on">
    <h3>Bring your own key</h3><div class="price">Free</div><div class="unit">your key</div>
    <ul>
      <li>Everything in Demo, with your own evidence</li>
      <li>Drafting runs on your provider account</li>
      <li>Your contract with that provider is the one that governs your text</li>
      <li>Documents hard deleted after 14 days</li>
    </ul>
    <div class="who2">For confidential evidence. The only party who can promise you anything
    about your text is the provider you already pay &mdash; so use them.</div>
  </div>

  <div class="tier">
    <h3>Managed</h3><div class="price">from $2,000</div><div class="unit">per month</div>
    <ul>
      <li>Our paid key under a no-training commitment, in contract</li>
      <li>Retention, residency and deletion become contract terms</li>
      <li>We onboard your corpus and keep it current</li>
      <li>Your trust page generated and maintained</li>
      <li>Named support, and a signed DPA</li>
    </ul>
    <div class="who2">For a team whose security review is holding up deals and who need the
    commitments to be contractual rather than a page on a website.</div>
  </div>
</div>

<h2 class="sec">Done for you</h2>
<p class="lede">If you would rather not operate anything at all, we run the engagement: you forward
the questionnaire and get it back answered, cited, and ready for your sign-off, together with the
evidence-gap worklist that makes the next one cheaper. <b>From $6,000 per month</b>, or
<b>$1,500&ndash;2,500</b> for a single questionnaire once your corpus is onboarded. An enterprise
questionnaire costs a security analyst eight to twenty hours; this replaces that, every time.</p>

<h2 class="sec">What is not included, stated plainly</h2>
<ul class="pts">
  <li><b>We do not produce evidence you do not have.</b> If there is no penetration test, the
      engine refuses the penetration test question and tells you so. Buying this does not create
      controls.</li>
  <li><b>We do not sign your representations.</b> A named person on your side approves every answer
      that goes out. That is the design, not a limitation.</li>
  <li><b>We do not answer contractual commitments.</b> Liability, indemnities, uptime guarantees and
      penalties route to your counsel before anything is drafted.</li>
  <li><b>No uptime commitment.</b> The service runs as a single instance by design. That is on our
      <a href="/trust/">trust centre</a> too, because you would find out eventually.</li>
</ul>
"""
    return shell("Pricing — Constat", "/pricing/",
                 head("Free to try with your own key. Paid when you need it in a contract.",
                      "Three modes, and the difference between them is whose contract governs your "
                      "text &mdash; not how many features you get."),
                 body, "Constat pricing: demo, bring your own key, and managed.")


def main() -> int:
    trust_html, trust_data = build_trust()
    pages = {"trust": trust_html, "how-it-works": build_how(), "pricing": build_pricing()}
    for name, markup in pages.items():
        target = SITE / name / "index.html"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(markup, encoding="utf-8")
        print(f"  wrote site/{name}/index.html ({target.stat().st_size // 1024}KB)")
    print(f"trust centre: {trust_data['published']}/{trust_data['questions']} answered "
          f"({trust_data['deflection_rate']:.1%} deflection)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
