"""Shoot the source material for the demo film off the real hosted product.

Boots the actual stdlib server (constat.server.app) against a throwaway data
dir and drives it with Playwright exactly like a calm human would -- signup,
empty workspace, seed the sample pack, run the questionnaire with the offline
mock drafter, read the report.

TWO CAPTURE MODES, AND WHY THE DEFAULT CHANGED
----------------------------------------------
The first version of this script recorded a Playwright video at the 1280x800
viewport, downscaled to 960x600, and scripts/produce_demo_video.py cut its
punch-ins out of that.  That is where the blur came from: a 2.13x punch-in
crops ~450x281 real pixels out of a 960-wide frame and stretches them back to
960x600.  No resampling filter can invent the missing detail, so every zoom in
the film was a genuine upscale and the UI body text went soft.

Playwright's video recorder composites at the viewport size and does NOT honour
device_scale_factor, so there is no high-resolution video to be had from it.
What DOES honour device_scale_factor is page.screenshot(): at dsf=3 a 1280x800
viewport screenshots at a true 3840x2400 (measured, not assumed -- the manifest
records the real decoded size and produce_demo_video.py refuses to run if it is
under 2560 wide).

The film is 80% dead-still holds and the six footage shots are static UI states
with a moving camera, so the master is now a set of high-resolution STILLS, one
per beat, plus a short burst wherever the old footage actually moved (the seed
landing, the run click and the running progress bar).  Every punch-in is now a
DOWNSAMPLE of 3840-wide pixels; nothing is ever upscaled.

    master (default)   .demo_master/*.png + manifest.json  -> produce_demo_video.py
    --raw (optional)   site/img/demo.webm + demo_poster.jpg

The raw webm is only the legacy fallback <source> on the marketing page (the
produced cut is what actually plays), so it is no longer regenerated by
default; passing --raw re-records it exactly as before.

Regenerate with:
    .venv/bin/python scripts/capture_demo_video.py           # stills master
    .venv/bin/python scripts/capture_demo_video.py --raw     # legacy webm too
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENV_PY = ROOT / ".venv" / "bin" / "python"
CHROME = "/opt/pw-browsers/chromium-1194/chrome-linux/chrome"
PW_FFMPEG = "/opt/pw-browsers/ffmpeg-1011/ffmpeg-linux"

PORT = int(os.environ.get("DEMO_PORT", "8872"))
BASE = f"http://127.0.0.1:{PORT}"
# A scratch dir for the throwaway tenant this script creates. It used to be a
# hardcoded session path, which the Constat rename then rewrote into a path that
# had never existed. Derive it instead, so it cannot go stale again.
DATA_DIR = Path(os.environ.get(
    "DEMO_DATA", tempfile.gettempdir() + "/constat_viddata"))
WORK = DATA_DIR.parent / "vidwork"

OUT_VIDEO = ROOT / "site" / "img" / "demo.webm"
OUT_POSTER = ROOT / "site" / "img" / "demo_poster.jpg"
VIDEO_BUDGET = 2_200_000       # bytes
POSTER_BUDGET = 60_000         # bytes

VIEWPORT = {"width": 1280, "height": 800}

# ---------------------------------------------------------------- master ----
# The high-resolution master.  dsf=3 gives 3840x2400 PNGs at ~0.35MB each and
# ~0.46s a shot, which is fast enough to burst through the run click.  The
# whole master is ~15 files; it is an intermediate, not a site asset, so it
# lives outside site/ and is gitignored.
MASTER_DIR = Path(os.environ.get("DEMO_MASTER", ROOT / ".demo_master"))
MASTER_DSF = int(os.environ.get("DEMO_MASTER_DSF", "3"))
MASTER_MIN_W = 2560            # produce_demo_video.py enforces this too


# ---------------------------------------------------------------- server ----
def start_server() -> subprocess.Popen:
    env = {**os.environ, "CONSTAT_DATA": str(DATA_DIR), "PORT": str(PORT)}
    # the film must show the deterministic offline drafter, never a live model
    env.pop("GEMINI_API_KEY", None)
    proc = subprocess.Popen(
        [str(VENV_PY), "-m", "constat.server.app",
         "--host", "127.0.0.1", "--port", str(PORT)],
        cwd=ROOT, env=env,
        stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
    deadline = time.time() + 20
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(f"{BASE}/healthz", timeout=2) as r:
                if json.loads(r.read()).get("ok"):
                    return proc
        except Exception:
            time.sleep(0.3)
        if proc.poll() is not None:
            break
    err = proc.stderr.read().decode() if proc.stderr else ""
    raise SystemExit(f"server did not come up on {BASE}\n{err}")


def signup() -> str:
    body = json.dumps({"org": "Northwind Systems",
                       "email": "security@northwind.example",
                       "consent": True}).encode()
    req = urllib.request.Request(
        f"{BASE}/api/signup", data=body,
        headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=10) as r:
        data = json.loads(r.read())
    if "workspace" not in data:
        raise SystemExit(f"signup failed: {data}")
    return data["workspace"]      # /t/<slug>?k=<token>


# ------------------------------------------------------------- the film ----
def smooth_scroll(page, y: int, settle_ms: int = 1600) -> None:
    page.evaluate(f"window.scrollTo({{top: {y}, behavior: 'smooth'}})")
    page.wait_for_timeout(settle_ms)


def smooth_to(page, selector: str, settle_ms: int = 1800) -> bool:
    found = page.evaluate(
        """(sel) => {
            const el = document.querySelector(sel);
            if (!el) return false;
            el.scrollIntoView({behavior: 'smooth', block: 'center'});
            return true;
        }""", selector)
    page.wait_for_timeout(settle_ms)
    return bool(found)


def film(workspace_path: str, video_dir: Path, poster_raw: Path) -> Path:
    from playwright.sync_api import sync_playwright

    with sync_playwright() as pw:
        browser = pw.chromium.launch(
            executable_path=CHROME, headless=True,
            args=["--no-sandbox", "--disable-dev-shm-usage",
                  "--force-device-scale-factor=1", "--hide-scrollbars"])
        ctx = browser.new_context(
            viewport=VIEWPORT, record_video_dir=str(video_dir),
            record_video_size=VIEWPORT, device_scale_factor=1)
        page = ctx.new_page()

        # 1 — the empty workspace, fresh from signup
        page.goto(BASE + workspace_path, wait_until="networkidle")
        page.wait_for_timeout(2200)

        # 2 — seed the sample evidence pack, watch documents land
        smooth_to(page, "#seedbtn", 900)
        page.click("#seedbtn")
        page.wait_for_selector("#docs .doc", timeout=15_000)
        page.wait_for_timeout(1400)
        smooth_to(page, "#docs", 1200)
        page.wait_for_timeout(1600)

        # 3 — start the run; the offline drafter shows per-question progress
        page.wait_for_function(
            "() => !document.getElementById('runbtn').disabled", timeout=15_000)
        smooth_to(page, "#runbtn", 1000)
        page.click("#runbtn")
        # let the ticker play: progress bar, then the completion card
        page.wait_for_selector("#resultcard", timeout=180_000)
        page.wait_for_timeout(600)
        smooth_to(page, "#resultcard", 1200)
        page.wait_for_timeout(2200)

        # 4 — the run report, read like a human: dial, tiles, refusals,
        #     one refusal's provenance
        href = page.get_attribute("#resultcard a.abtn-primary", "href")
        page.goto(BASE + href, wait_until="networkidle")
        page.wait_for_timeout(1800)
        page.screenshot(path=str(poster_raw), type="jpeg", quality=88)

        smooth_to(page, ".viz", 2000)               # coverage dial + stat tiles
        page.wait_for_timeout(1200)
        smooth_to(page, ".stackbar", 2000)          # the refusal bar
        page.wait_for_timeout(1200)
        # one refusal's provenance line ("no citation released · gap named")
        if not smooth_to(page, ".prov.p-warn", 2200):
            smooth_to(page, "table tbody tr:nth-child(4)", 2200)
        page.wait_for_timeout(1600)
        smooth_scroll(page, 0, 1800)                # settle back on the verdict
        page.wait_for_timeout(800)

        page.close()
        video_path = Path(page.video.path())
        ctx.close()
        browser.close()
    return video_path


# --------------------------------------------------------- master stills ----
# One entry per footage shot in scripts/produce_demo_video.py, in film order.
#
# `weights` are relative durations inside the shot's camera move, measured off
# the ORIGINAL capture so the re-shot master keeps the old cutting rhythm to
# the frame.  The numbers below are old-footage frame counts:
#
#   seed  (old f90-f123, 34 frames)  7 frames of the refresh still settling,
#                                    then 27 of the settled list
#   run   (old f210-f251, 42 frames) 7 frames before the click, then 35 of the
#                                    running state with its sweeping bar
#   everything else is a genuinely static window in the old footage (measured
#   mean inter-frame delta 0.009-0.06 of a grey level), so one still is a
#   truthful reproduction of it, not a simplification.
#
# `scroll` is the selector the old capture centred for that beat; centring is
# deterministic, so the framing the SHOTS table was composed against comes back
# byte-for-byte at any device scale factor.
BEAT_ORDER = ["seed", "run", "complete", "reporttop", "stackbar", "provenance"]


def _shoot(page, out_dir: Path, key: str, idx: int) -> dict:
    path = out_dir / f"{key}_{idx:03d}.png"
    page.screenshot(path=str(path))
    return {"file": path.name}


def film_master(workspace_path: str, out_dir: Path) -> dict:
    """Walk the same journey and stop at each beat to take a high-resolution
    still (or a short burst where the old footage moved)."""
    from playwright.sync_api import sync_playwright
    from PIL import Image

    beats: dict[str, dict] = {}

    def beat(key, page, stills, weights, scroll_sel):
        beats[key] = {
            "scroll": scroll_sel,
            "scroll_y": page.evaluate("window.scrollY"),
            "stills": [{**s, "w": float(w)} for s, w in zip(stills, weights)],
        }
        print(f"  {key:11s} {len(stills)} still(s)  scrollY="
              f"{beats[key]['scroll_y']:.0f}  w={[round(x, 2) for x in weights]}")

    def centre(page, selector: str, settle_ms: int = 700) -> bool:
        found = page.evaluate(
            """(sel) => {
                const el = document.querySelector(sel);
                if (!el) return false;
                el.scrollIntoView({block: 'center'});
                return true;
            }""", selector)
        page.wait_for_timeout(settle_ms)
        return bool(found)

    with sync_playwright() as pw:
        browser = pw.chromium.launch(
            executable_path=CHROME, headless=True,
            args=["--no-sandbox", "--disable-dev-shm-usage", "--hide-scrollbars"])
        # no record_video_dir: the recorder ignores device_scale_factor, and a
        # 960-wide video is exactly the thing this rewrite exists to delete
        ctx = browser.new_context(viewport=VIEWPORT,
                                  device_scale_factor=MASTER_DSF)
        page = ctx.new_page()

        page.goto(BASE + workspace_path, wait_until="networkidle")
        page.wait_for_timeout(1500)

        # --- beat 1: the seed lands -------------------------------------
        centre(page, "#seedbtn", 400)
        page.click("#seedbtn")
        page.wait_for_selector("#docs .doc", timeout=15_000)
        # first still catches the refresh still settling (the seed button is
        # still dimmed), the second the settled 13/20 counter and chip rows
        s0 = _shoot(page, out_dir, "seed", 0)
        page.wait_for_timeout(900)
        s1 = _shoot(page, out_dir, "seed", 1)
        beat("seed", page, [s0, s1], [7, 27], "#seedbtn")

        # --- beat 2: ten questions, one click ---------------------------
        page.wait_for_function(
            "() => !document.getElementById('runbtn').disabled", timeout=15_000)
        centre(page, "#runbtn", 500)
        pre = _shoot(page, out_dir, "run", 0)          # 3 of 3 runs remaining
        page.click("#runbtn")
        # burst while the run is live: the indeterminate <progress> sweeps, so
        # each still catches a different bar phase and the hold lands on the
        # running state exactly as the old cut did
        burst = []
        for k in range(6):
            if page.query_selector("#resultcard"):
                break
            still = _shoot(page, out_dir, "run", 1 + k)
            # the run can finish DURING the exposure, and the LAST still of
            # this beat is the one the 3.25s hold freezes on -- so a still
            # that caught the verdict card would land the payoff a whole shot
            # early, before the act card that introduces it. Check after the
            # shutter, not only before it, and throw that frame away.
            if page.query_selector("#resultcard"):
                (out_dir / still["file"]).unlink()
                break
            burst.append(still)
        if not burst:
            raise SystemExit("the run finished before a single running still "
                             "could be taken; the beat would lose its state")
        weights = [7] + [35 / len(burst)] * len(burst)
        beat("run", page, [pre, *burst], weights, "#runbtn")

        # --- beat 3: the verdict card -----------------------------------
        page.wait_for_selector("#resultcard", timeout=180_000)
        page.wait_for_timeout(900)
        centre(page, "#resultcard", 900)
        beat("complete", page, [_shoot(page, out_dir, "complete", 0)], [1],
             "#resultcard")

        # --- beats 4-6: the run report ----------------------------------
        href = page.get_attribute("#resultcard a.abtn-primary", "href")
        page.goto(BASE + href, wait_until="networkidle")
        page.wait_for_timeout(1400)
        beat("reporttop", page, [_shoot(page, out_dir, "reporttop", 0)], [1],
             "top")

        centre(page, ".stackbar", 800)
        beat("stackbar", page, [_shoot(page, out_dir, "stackbar", 0)], [1],
             ".stackbar")

        sel = ".prov.p-warn"
        if not centre(page, sel, 800):
            sel = "table tbody tr:nth-child(4)"
            centre(page, sel, 800)
        beat("provenance", page, [_shoot(page, out_dir, "provenance", 0)], [1],
             sel)

        ctx.close()
        browser.close()

    # the real decoded size of what we actually got, never the size we asked
    # for -- this is the number produce_demo_video.py gates on
    probe = Image.open(out_dir / beats["seed"]["stills"][0]["file"])
    mw, mh = probe.size
    for key in BEAT_ORDER:
        if key not in beats:
            raise SystemExit(f"beat {key} never got shot")
        for s in beats[key]["stills"]:
            w, h = Image.open(out_dir / s["file"]).size
            if (w, h) != (mw, mh):
                raise SystemExit(f"{s['file']} is {w}x{h}, master is {mw}x{mh}")
    if mw < MASTER_MIN_W:
        raise SystemExit(
            f"master is only {mw}px wide; every punch-in would upscale again. "
            f"Raise DEMO_MASTER_DSF (need >= {MASTER_MIN_W}).")
    if mw * VIEWPORT["height"] != mh * VIEWPORT["width"]:
        raise SystemExit(f"master {mw}x{mh} is not the viewport's 8:5")

    return {
        "viewport": VIEWPORT,
        "device_scale_factor": MASTER_DSF,
        "width": mw,
        "height": mh,
        "order": BEAT_ORDER,
        "beats": beats,
    }


# ------------------------------------------------------------ compression ----
def pick_ffmpeg() -> tuple[str, str]:
    """Returns (binary, codec). Prefers a full ffmpeg (VP9); falls back to
    Playwright's bundled build, which only carries the VP8 encoder."""
    full = shutil.which("ffmpeg")
    if full:
        return full, "vp9"
    if Path(PW_FFMPEG).is_file():
        return PW_FFMPEG, "vp8"
    raise SystemExit("no ffmpeg available to compress the recording")


def transcode(ffmpeg: str, codec: str, src: Path, dst: Path) -> int:
    """Scale to 960 wide, 24fps, no audio; step quality down until under
    budget. Returns the final byte size."""
    if codec == "vp9":
        attempts = [["-c:v", "libvpx-vp9", "-crf", str(crf), "-b:v", "0"]
                    for crf in (42, 47, 52)]
    else:
        attempts = [["-c:v", "libvpx", "-crf", "30", "-b:v", bv,
                     "-qmin", "4", "-qmax", "50"]
                    for bv in ("480k", "380k", "300k")]
    for extra in attempts:
        cmd = [ffmpeg, "-y", "-i", str(src),
               "-vf", "scale=960:-2", "-r", "24", "-an",
               *extra, "-deadline", "good", "-cpu-used", "2", str(dst)]
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL,
                       stderr=subprocess.DEVNULL)
        size = dst.stat().st_size
        if size <= VIDEO_BUDGET:
            return size
    return dst.stat().st_size


def make_poster(raw: Path, dst: Path) -> int:
    from PIL import Image
    img = Image.open(raw).convert("RGB")
    w = 960
    h = round(img.height * w / img.width)
    img = img.resize((w, h), Image.LANCZOS)
    for q in (80, 72, 64, 55):
        img.save(dst, "JPEG", quality=q, optimize=True, progressive=True)
        if dst.stat().st_size <= POSTER_BUDGET:
            break
    return dst.stat().st_size


# --------------------------------------------------------------------- main --
def capture_raw(workspace: str) -> None:
    """The legacy 960x600 webm, kept because site/img/demo.webm is still the
    last-resort <source> on the page."""
    video_dir = WORK / "video"
    video_dir.mkdir(parents=True, exist_ok=True)
    poster_raw = WORK / "poster_raw.jpg"
    raw = film(workspace, video_dir, poster_raw)
    print(f"raw recording: {raw} ({raw.stat().st_size} bytes)")
    ffmpeg, codec = pick_ffmpeg()
    OUT_VIDEO.parent.mkdir(parents=True, exist_ok=True)
    vsize = transcode(ffmpeg, codec, raw, OUT_VIDEO)
    psize = make_poster(poster_raw, OUT_POSTER)
    print(f"{OUT_VIDEO}  {vsize} bytes  (codec {codec}, budget {VIDEO_BUDGET})")
    print(f"{OUT_POSTER}  {psize} bytes  (budget {POSTER_BUDGET})")
    if vsize > VIDEO_BUDGET:
        print("WARNING: video is over budget")
    if psize > POSTER_BUDGET:
        print("WARNING: poster is over budget")


def main() -> None:
    want_raw = "--raw" in sys.argv
    want_master = "--no-master" not in sys.argv

    if DATA_DIR.exists():
        shutil.rmtree(DATA_DIR)
    if WORK.exists():
        shutil.rmtree(WORK)
    DATA_DIR.mkdir(parents=True)
    WORK.mkdir(parents=True)

    proc = start_server()
    try:
        if want_master:
            if MASTER_DIR.exists():
                shutil.rmtree(MASTER_DIR)
            MASTER_DIR.mkdir(parents=True)
            # a workspace of its own: the run quota is 3 and the "3 of 3 runs
            # remaining" line is on screen in the questions beat, so the master
            # pass must not be sharing a workspace with the raw pass
            ws = signup()
            print(f"master workspace: {ws.split('?')[0]}")
            manifest = film_master(ws, MASTER_DIR)
            (MASTER_DIR / "manifest.json").write_text(
                json.dumps(manifest, indent=2))
            total = sum(p.stat().st_size for p in MASTER_DIR.glob("*.png"))
            print(f"master: {manifest['width']}x{manifest['height']} "
                  f"(dsf {manifest['device_scale_factor']}), "
                  f"{len(list(MASTER_DIR.glob('*.png')))} stills, "
                  f"{total:,d} bytes -> {MASTER_DIR}")
        if want_raw:
            capture_raw(signup())
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()


if __name__ == "__main__":
    main()
