"""Shared chrome for the public site.

The site is generated by the engine, not hand-written alongside it: the trust
center, the accuracy page and the metrics all come out of real runs. This
module holds only the parts that are not generated — the shell, the navigation
and the design tokens.

The palette and type scale are lifted directly from `report.CSS` so a page on
the website and an audit working paper produced by the engine read as the same
system. That is deliberate: the report is the product, and the marketing site
should not look like a different company made it.
"""
from __future__ import annotations

import html
from datetime import date

from .report import CSS as REPORT_CSS

BRAND = "Pramana"
TAGLINE = "Evidence-gated customer assurance"

# Primary navigation is the buyer's path: what it is, how we work, what you get,
# what it costs, and the proof. Everything else is real but secondary, and lives
# in the footer rather than competing for attention in the header.
NAV = [
    ("/", "Overview"),
    ("/how-it-works/", "How it works"),
    ("/deliverables/", "What you get"),
    ("/pricing/", "Pricing"),
    ("/trust/", "Trust center"),
    ("/accuracy/", "Accuracy"),
    ("/demo/", "Live demo"),
]

SECONDARY_NAV = [
    ("/security/", "Security posture"),
    ("/isolation/", "Tenant isolation"),
    ("/metrics/", "Outcome metrics"),
    ("/commitments/", "Commitment register"),
    ("/changelog/", "Changelog"),
]

SITE_CSS = """
body{padding:0}
.wrap{max-width:1080px}
nav.top{border-bottom:1px solid var(--line);background:var(--card);position:sticky;top:0;z-index:20}
nav.top .inner{max-width:1080px;margin:0 auto;padding:0 28px;display:flex;align-items:center;
gap:22px;flex-wrap:wrap;min-height:56px}
nav.top a.brand{font-family:"Space Grotesk",sans-serif;font-weight:600;font-size:17px;
color:var(--ink);text-decoration:none;letter-spacing:-.01em;margin-right:6px}
nav.top a.brand span{color:var(--ok)}
nav.top a.nl{font:600 11px/1 "IBM Plex Mono",monospace;letter-spacing:.1em;text-transform:uppercase;
color:var(--muted);text-decoration:none;padding:6px 0;border-bottom:2px solid transparent}
nav.top a.nl:hover{color:var(--ink)}
nav.top a.nl.on{color:var(--ok);border-bottom-color:var(--ok)}
.hero{padding:60px 0 34px;border-bottom:2px solid var(--ink);margin-bottom:34px}
.hero h1{font-family:"Space Grotesk",sans-serif;font-size:clamp(30px,5vw,50px);font-weight:600;
letter-spacing:-.02em;line-height:1.08;max-width:20ch}
.hero p.lede{margin-top:18px;font-size:17px;line-height:1.6;color:var(--muted);max-width:62ch}
.cta{display:flex;gap:12px;flex-wrap:wrap;margin-top:26px;align-items:center}
.btn{font:600 12px "IBM Plex Mono",monospace;letter-spacing:.08em;text-transform:uppercase;
padding:12px 20px;border:1.5px solid var(--ink);background:var(--card);color:var(--ink);
text-decoration:none;cursor:pointer;display:inline-block}
.btn.primary{background:var(--ink);color:var(--card);border-color:var(--ink)}
.btn:hover{border-color:var(--ok);color:var(--ok)}
.btn.primary:hover{background:var(--ok);color:var(--card);border-color:var(--ok)}
.cols{display:grid;grid-template-columns:repeat(auto-fit,minmax(268px,1fr));gap:14px;margin:22px 0}
.card{background:var(--card);border:1px solid var(--line);border-top:3px solid var(--ok);padding:18px 20px}
.card h3{font-family:"Space Grotesk",sans-serif;font-size:16px;font-weight:600;margin-bottom:8px}
.card p{font-size:13.5px;line-height:1.6;color:var(--muted)}
.card.warn{border-top-color:var(--warn)} .card.rev{border-top-color:var(--rev)}
.lead{font-size:15px;line-height:1.65;max-width:70ch;margin-bottom:14px}
ul.tight{margin:10px 0 16px 20px} ul.tight li{font-size:14px;line-height:1.65;margin-bottom:7px}
code{font:12.5px "IBM Plex Mono",monospace;background:var(--okbg);padding:1px 5px;border:1px solid var(--line)}
pre{background:var(--ink);color:#DDE7E0;padding:16px 18px;overflow-x:auto;font:12.5px/1.65 "IBM Plex Mono",monospace;
margin:14px 0;border-left:3px solid var(--ok)}
pre code{background:none;border:none;color:inherit;padding:0}
.note{border-left:3px solid var(--warn);background:var(--warnbg);padding:12px 16px;margin:16px 0;font-size:13.5px;line-height:1.6}
.note b{color:var(--warn)}
.tablewrap{overflow-x:auto;margin:16px 0}
.stamp{font:11px/1.7 "IBM Plex Mono",monospace;color:var(--muted);margin-top:10px}
form.waitlist{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-top:8px}
form.waitlist input{font:14px "IBM Plex Sans",system-ui,sans-serif;padding:11px 13px;border:1.5px solid var(--line);
background:var(--card);color:var(--ink);min-width:260px;flex:1}
form.waitlist input:focus{outline:none;border-color:var(--ok)}
.formmsg{font:12px "IBM Plex Mono",monospace;margin-top:10px;display:none}
.formmsg.ok{color:var(--ok);display:block} .formmsg.err{color:var(--bad);display:block}
footer.site{margin-top:56px;padding:22px 0 60px;border-top:2px solid var(--ink);
font:11px/1.8 "IBM Plex Mono",monospace;color:var(--muted)}
footer.site a{color:var(--ok)}
.steps{counter-reset:step;margin:22px 0}
.step{position:relative;padding:0 0 22px 52px;border-left:2px solid var(--line);margin-left:16px}
.step:last-child{border-left-color:transparent;padding-bottom:0}
.step:before{counter-increment:step;content:counter(step);position:absolute;left:-17px;top:-2px;
width:32px;height:32px;border-radius:50%;background:var(--ink);color:var(--card);
font:700 13px/32px "IBM Plex Mono",monospace;text-align:center}
.step h3{font-family:"Space Grotesk",sans-serif;font-size:16px;font-weight:600;margin-bottom:6px}
.step p{font-size:14px;line-height:1.65;color:var(--muted);max-width:64ch}
.step .who{font:600 10px "IBM Plex Mono",monospace;letter-spacing:.12em;text-transform:uppercase;
color:var(--ok);margin-bottom:4px;display:block}
.tiers{display:grid;grid-template-columns:repeat(auto-fit,minmax(268px,1fr));gap:14px;margin:24px 0}
.tier{background:var(--card);border:1px solid var(--line);border-top:3px solid var(--line);padding:22px}
.tier.feature{border-top-color:var(--ok);box-shadow:0 1px 0 var(--line)}
.tier h3{font-family:"Space Grotesk",sans-serif;font-size:17px;font-weight:600}
.tier .price{font-family:"Space Grotesk",sans-serif;font-size:27px;font-weight:600;margin:10px 0 2px}
.tier .unit{font:11px "IBM Plex Mono",monospace;color:var(--muted);text-transform:uppercase;letter-spacing:.1em}
.tier ul{margin:14px 0 0 18px} .tier li{font-size:13.5px;line-height:1.6;margin-bottom:6px}
.tier .who{font:12px/1.55 "IBM Plex Mono",monospace;color:var(--muted);margin-top:14px;
padding-top:12px;border-top:1px solid var(--line)}
.kv{display:grid;grid-template-columns:auto 1fr;gap:8px 18px;margin:16px 0;font-size:14px}
.kv dt{font:600 11px "IBM Plex Mono",monospace;letter-spacing:.1em;text-transform:uppercase;
color:var(--muted);padding-top:3px}
.kv dd{line-height:1.6}
.filelist{background:var(--card);border:1px solid var(--line);padding:4px 0;margin:16px 0}
.filerow{display:flex;gap:14px;align-items:baseline;padding:11px 18px;border-bottom:1px solid var(--line)}
.filerow:last-child{border-bottom:none}
.filerow .fn{font:600 12px "IBM Plex Mono",monospace;color:var(--ok);white-space:nowrap;min-width:210px}
.filerow .fd{font-size:13.5px;line-height:1.55;color:var(--muted)}
@media(max-width:640px){.filerow{flex-direction:column;gap:4px}.filerow .fn{min-width:0}}
@media(max-width:640px){nav.top .inner{gap:14px;padding:10px 18px}.wrap{padding:0 18px}}
"""

FONTS = ('<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600'
         '&family=IBM+Plex+Sans:wght@400;600&family=IBM+Plex+Mono:wght@400;600;700'
         '&display=swap" rel="stylesheet">')


def esc(text: str) -> str:
    return html.escape(str(text), quote=False)


# Only routes the build actually produced appear in the navigation. A link to a
# page that does not exist yet is a small lie, and this site's entire argument is
# that the product does not make those.
_AVAILABLE: set[str] = {href for href, _ in NAV} | {href for href, _ in SECONDARY_NAV}


def set_available(routes: set[str]) -> None:
    global _AVAILABLE
    _AVAILABLE = set(routes)


def nav_html(active: str) -> str:
    links = "".join(
        f'<a class="nl{" on" if href == active else ""}" href="{href}">{esc(label)}</a>'
        for href, label in NAV if href in _AVAILABLE)
    return (f'<nav class="top"><div class="inner">'
            f'<a class="brand" href="/">Pramana<span>.</span></a>{links}</div></nav>')


def footer_nav() -> str:
    live = [(href, label) for href, label in SECONDARY_NAV if href in _AVAILABLE]
    if not live:
        return ""
    return " · ".join(f'<a href="{href}">{esc(label)}</a>' for href, label in live)


def page(title: str, body: str, active: str = "/", description: str = "",
         generated: date | None = None) -> str:
    stamp = (generated or date.today()).isoformat()
    secondary = footer_nav()
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{html.escape(description or TAGLINE, quote=True)}">
{FONTS}
<style>{REPORT_CSS}{SITE_CSS}</style></head><body>
{nav_html(active)}
<div class="wrap">
{body}
<footer class="site">
{secondary}{"<br>" if secondary else ""}
{esc(BRAND)} · {esc(TAGLINE)} · page generated {stamp}<br>
All client data shown is synthetic. Source: <a href="https://github.com/dhruvshahi10/pramana">github.com/dhruvshahi10/pramana</a>
</footer>
</div></body></html>"""


def hero(headline: str, lede: str, cta: str = "") -> str:
    return (f'<div class="hero"><h1>{esc(headline)}</h1>'
            f'<p class="lede">{lede}</p>{cta}</div>')
